// File: output.ts
// Location: src/output.ts

import * as path from 'path';
import * as vscode from 'vscode';

export function formatMarkdownOutput(rootUri: vscode.Uri, treeLines: string[]): string {
  const folderName = path.basename(rootUri.fsPath) || rootUri.fsPath;
  const generatedAt = formatDateTime(new Date());
  const rootPath = rootUri.fsPath;

  return [
    `# File Tree: ${folderName}`,
    '',
    `**Generated:** ${generatedAt}`,
    `**Root Path:** \`${rootPath}\``,
    '',
    '```',
    ...treeLines,
    '```',
    '',
    '---',
    '*Generated by File Tree Smart*',
  ].join('\n');
}

function formatDateTime(date: Date): string {
  const formatter = new Intl.DateTimeFormat('en-GB', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: false,
  });

  const parts = formatter.formatToParts(date);
  const day = parts.find((part) => part.type === 'day')?.value ?? '00';
  const month = parts.find((part) => part.type === 'month')?.value ?? '00';
  const year = parts.find((part) => part.type === 'year')?.value ?? '0000';
  const hour = parts.find((part) => part.type === 'hour')?.value ?? '00';
  const minute = parts.find((part) => part.type === 'minute')?.value ?? '00';
  const second = parts.find((part) => part.type === 'second')?.value ?? '00';

  return `${day}/${month}/${year}, ${hour}:${minute}:${second}`;
}

export async function showMarkdownDocument(content: string): Promise<void> {
  const doc = await vscode.workspace.openTextDocument({
    language: 'markdown',
    content,
  });

  await vscode.window.showTextDocument(doc, {
    preview: false,
  });
}
